### ISSUE TITLE
Why it is not recognized

### ISSUE THREAD

**Issue by dungnart** [cyber-z/public-fox-android-sdk#32]
Please help me with this issue:
![image](https://cloud.githubusercontent.com/assets/9654516/15739412/1feddb18-28da-11e6-9182-b5d77886f4f5.png)

I have declared in `onCreate()` method: 

`  AdManager ad = new AdManager(this);   
ad.sendConversion();`

also in `onResume()` method:
`    protected void onResume() {
        super.onResume();
        AdManager ad = new AdManager(this);
 ad.sendReengagementConversion(getIntent());
AnalyticsManager.sendStartSession(this);`

**Comment by czhiraga** [comment]
Thank you for the message.
Please let me see the AndroidManifest.xml on your project.

**Comment by dungtndev** [comment]
Thanks for your support. Here is my AndroidMainifest.xml file. Hope that
hear from you soon.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="jp.soroeru.app">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"
/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission
android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    
    <uses-permission
android:name="com.google.android.c2dm.permission.RECEIVE" />
    
    <permission
        android:name="jp.soroeru.app.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="jp.soroeru.app.permission.C2D_MESSAGE" />

    <application
        android:name=".SoroeruApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
   >
        <activity
            android:name=".activities.HomeActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan|adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".activities.MainActivity"
            android:configChanges="keyboard|orientation"
            android:label="@string/title_activity_main"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan|adjustResize"></activity>
        <activity
            android:name=".activities.WebActivity"
            android:label="@string/title_activity_web"
            android:screenOrientation="portrait"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:windowSoftInputMode="adjustPan|adjustResize"></activity>

        
        <receiver
            android:name=".GCMBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action
android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action
android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <category android:name="com.androidsrc.gcmsample" />
            </intent-filter>
        </receiver>

        <service android:name=".GCMIntentService" />

    </application>

</manifest>
On Jun 3, 2016 5:08 PM, "Garhira" <notifications@github.com> wrote:

Thank you for the message.
Please let me see the AndroidManifest.xml on your project.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cyber-z/public-fox-android-sdk/issues/32#issuecomment-223541812>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJNQ9FtyxhnrlNdBt0eyw8XRkBheFKr9ks5qH_0tgaJpZM4IsVpt>
.

**Comment by dungtndev** [comment]
@czhiraga: Would you like to help me solve this problem ? Thanks a lot.

**Comment by czhiraga** [comment]
There is no problem about your AndroidManifest.xml.
We have a bug in server and have been doing with it.
Don't worry about your test, it is OK.
We have corrected your test status, you can go to the next step.
